### ISSUE TITLE
Updating runner info fails on stage-collector but not locally...

### ISSUE THREAD

**Issue by zakkak** [Karm/collector#27] opened 2024-04-24 06:56 UTC
Trying to update runner-info in stage-collector.foci.life fails with:

```
{"exceptionType":"io.quarkus.arc.ArcUndeclaredThrowableException","code":500,"error":"Error invoking subclass method"}
```

While the same request succeeds locally.

The request is:
```
curl -v -w '\n' -H "Content-Type: application/json" -H "token: $MY_RW_TOKEN" \                                                                     
     -X POST --data "@./runner-info.json" "https://stage-collector.foci.life/api/v1/image-stats/update-runner-info/199002"
```

and runner-info.json contains:

```json
{
  "testVersion": "2024-03-29-upload-native-build-stats",
  "mandrelVersion": null,
  "quarkusVersion": "ad6c821829016041bc5b123349d5a96113184da9",
  "jdkVersion": "",
  "operatingSystem": "Linux",
  "architecture": "X64",
  "memorySizeBytes": "16757346304",
  "memorySizeAvailableBytes": "14959022080",
  "description": "Quarkus CI github runner on 2024-03-29-upload-native-build-stats branch/tag"
}
```

**Comment by zakkak** [comment] 2024-04-24 06:57
@Karm could you please have a look at the logs to see if there is something useful there?

**Comment by jerboaa** [comment] 2024-04-25 09:21
@zakkak AFAIK, stage and prod uses native. Have you used native when trying to reproduce locally?

**Comment by zakkak** [comment] 2024-04-25 10:52
Tested with native and it still can't replicate locally.

**Comment by Karm** [comment] 2024-04-25 13:26
@zakkak The reason is the schema.
```
2024-04-25 13:21:35,137 WARN  [org.mar.jdb.mes.ser.ErrorPacket] (executor-thread-1) Error: 1364-HY000: Field 'memorySize' doesn't have a default value
```

You see, updating schema yielded a new attribute, but it left the old one there. Since it's not optional, doesn't have a default value, e.g. null, the insert fails.

![image](https://github.com/Karm/collector/assets/691097/dde9cf2c-15e8-494f-8414-fbfe4609dd80)

I have a refactor close to a PR. I suggest I polish it, post and if we agree we drop the unused columns.   Unless there is serious Runner Info data to migrate.

**Comment by zakkak** [comment] 2024-04-25 13:33
> I have a refactor close to a PR. I suggest I polish it, post and if we agree we drop the unused columns. Unless there is serious Runner Info data to migrate.

Sounds good to me. Thanks Karm.

**Comment by Karm** [comment] 2024-05-07 14:45
```
karm@laptop:/tmp$ curl  -w '\n' -H "Content-Type: application/json" -H "token: $TOKEN" -X POST --data "@./runner-info.json" "https://stage-collector.foci.life/api/v1/image-stats/update-runner-info/199002" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1654  100  1263  100   391   8533   2641 --:--:-- --:--:-- --:--:-- 11175
{
  "id": 199002,
  "created_at": "2024-04-24T06:27:56.228+00:00",
  "tag": "quarkus-main-ci",
  "img_name": "quarkus-integration-test-main-999-SNAPSHOT-runner",
  "generator_version": "Mandrel-23.1.2.0-Final",
  "image_size_stats": {
    "id": 199002,
    "total_bytes": 149214488,
    "code_cache_bytes": 66523840,
    "heap_bytes": 82255872,
    "resources_bytes": 9014096,
    "resources_count": 419,
    "other_bytes": 434776,
    "debuginfo_bytes": 0
  },
  "jni_classes_stats": {
    "id": 699005,
    "classes": 62,
    "fields": 63,
    "methods": 55
  },
  "reflection_stats": {
    "id": 699007,
    "classes": 9309,
    "fields": 489,
    "methods": 7955
  },
  "build_perf_stats": {
    "id": 199002,
    "total_build_time_sec": 248.266605981,
    "gc_time_sec": 40.699,
    "num_cpu_cores": 4,
    "total_machine_memory": 16757346304,
    "peak_rss_bytes": 5613408256,
    "cpu_load": 3.569375762635669
  },
  "total_classes_stats": {
    "id": 699008,
    "classes": 34162,
    "fields": 70806,
    "methods": 262751
  },
  "reachability_stats": {
    "id": 699006,
    "classes": 30959,
    "fields": 45169,
    "methods": 154089
  },
  "runner_info": {
    "id": 153,
    "test_version": null,
    "graalvm_version": null,
    "quarkus_version": null,
    "jdk_version": null,
    "operating_system": null,
    "architecture": "X64",
    "memory_size_bytes": 0,
    "memory_available_bytes": 0,
    "description": "Quarkus CI github runner on 2024-03-29-upload-native-build-stats branch/tag",
    "triggered_by": null,
    "created_at": "2024-05-07T14:45:14.065+00:00"
  }
}

```

Fixed by altering the schema.

**Closed by Karm** 2024-05-07 14:45 UTC

**Comment by Karm** [comment] 2024-05-07 14:46
My commentary on ideas how to use RunnerInfo:   https://github.com/Karm/mandrel-integration-tests/pull/258/files#diff-0a6869dbdb50678fc51a897c588aa2100fdcc3b6045d9e0e13b6b09ce30e3218
